%%
%%%
%%
im_1=imread('C:\Users\11054\Desktop\test\BBSO\2011\bbso_halph_fl_20110715_180110.jpg');
figure('Name','image_1');
imshow(im_1);
im_1=imadjust(im_1,[],[],1);
figure('Name','image_1_adjust');
imshow(im_1);
%空域滤波
im_2=imfilter(im_1,fspecial('average',5));
im_3=imfilter(im_2,fspecial('average',3));
figure('Name','image_2');
imshow(im_2);
figure('Name','image_3');
imshow(im_3);
im_bif=bilateralFilter(im2double(im_3));
figure('Name','bilateralFilter');
imshow(im_bif);

%频域滤波
PQ=paddedsize(size(im_1));
D0=0.05*PQ(1);
H1=highpassfilter('gaussian',PQ(1),PQ(2),0.001*D0);
g1=dftfilt(im_1,H1);
figure('Name','Highpassfilter');
imshow(g1);
L1=lowpassfilter('gaussian',PQ(1),PQ(2),D0);
g2=dftfilt(im_1,L1);
figure('Name','Lowpassfilter');
imshow(g2);